// Generated by TMB: do not edit by hand

#define TMB_LIB_INIT R_init_losmix_TMBExports
#include <TMB.hpp>
#include "mNIX_NLL.hpp"

template<class Type>
Type objective_function<Type>::operator() () {
  DATA_STRING(model_name);
  if(model_name == "mNIX_NLL") {
    return mNIX_NLL(this);
  } else {
    error("Unknown model_name.");
  }
  return 0;
}
